//! mussh Runtime Errors
use std::error;
use std::fmt;

#[derive(Debug)]
/// Errors generated by the mussh at rumtime.
pub enum MusshErr {
    /// Unknown Error
    Unknown
}

impl fmt::Display for MusshErr {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            MusshErr::Unknown => write!(f, "Unknown error"),
        }
    }
}

impl error::Error for MusshErr {
    fn description(&self) -> &str {
        match *self {
            MusshErr::Unknown => "Unknown error",
        }
    }

    fn cause(&self) -> Option<&error::Error> {
        match *self {
            MusshErr::Unknown => None,
        }
    }
}
